#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Feb  3 14:49:52 2022

@author: xies
"""

import numpy as np
import pandas as pd
from glob import glob
from os import path

import seaborn as sb

dirname = '/Users/xies/Box/Mouse/Skin/Two photon/NMS/20200925_F7_right ear_for Shicong'

#%%

Ncell = 10
cell_type = ['K10neg_divisions','K10pos_divisions']

cells = []
for ctype in cell_type:
    
    for i in range(Ncell):
    
        time_csvs = glob( path.join(dirname,ctype,'Cell'+str(i+1),'t[1-3].csv') )
        
        # Use glob since some cells are missing time points
        volumes = []
        day2div = []
        for fname in time_csvs:
            this_frame = pd.read_csv(fname)
            volumes.append(this_frame['Area'].sum())
            day2div.append(int(path.splitext(fname)[0][-1]) - 3)
        
        this_cell = pd.DataFrame()
        this_cell['Volume'] = volumes
        this_cell['Time'] = day2div
        this_cell['Cell type'] = ctype
        this_cell['CellID'] = i
        this_cell['Daughter']= False
        
        # Add daughter volumes together and mark
        daughter_a = pd.read_csv( path.join(dirname,ctype,'Cell'+str(i+1),'a.csv') )
        daughter_b = pd.read_csv( path.join(dirname,ctype,'Cell'+str(i+1),'b.csv') )
        
        daughter_volume_sum = daughter_a['Area'].sum() + daughter_b['Area'].sum()
        s = pd.Series({'Volume':daughter_volume_sum , 'CellID': i,
                       'Time': 1, 'Cell type': ctype,
                       'Daughter': True})
        
        this_cell = this_cell.append(s,ignore_index=True)
    
        cells.append(this_cell)
    
ts = pd.concat(cells,ignore_index=True)
sb.catplot(data = ts,x='Cell type',y='Volume', hue='Time')

no_daughter = ts[~ts.Daughter]

#%% Plot

# Plot growth curve cell by cell
for cell in cells:
    
    
    
    if cell.iloc[0]['Cell type'] == 'K10neg_divisions':
        color = 'g'
    elif cell.iloc[0]['Cell type'] == 'K10pos_divisions':
        color = 'm'
        
        
    time = cell['Time'].values[0:3]
    vol = cell['Volume'].values[:3]
    
    plot(time,vol,color=color)
        
    
        

        